!(import! &self petta_chainer)

!(compileadd kb (: weakFact (WeakPremise) (STV 1.0 0.1)))

!(compileadd kb (: baseFact (BasePremise) (STV 1.0 1.0)))

!(compileadd kb
   (: ruleHighThenDrop (Implication (Premises (WeakPremise) (BasePremise)) (Conclusions (SwitchGoal))) (STV 1.0 0.9)))

!(compileadd kb
   (: ruleStable (Implication (Premises (BasePremise)) (Conclusions (SwitchGoal))) (STV 1.0 0.7)))

!(test
   (let (: (rule-proof ruleStable baseFact) (SwitchGoal) (STV 1.0 0.63))
      (superpose (collapse
                  (query 10 kb (: $prf (SwitchGoal) $tv))))
      true)
   true)

!(test
   (let (: (rule-proof ruleHighThenDrop (conjunction weakFact baseFact)) (SwitchGoal) (STV 1.0 0.1))
      (superpose (collapse
                  (query 30 kb (: $prf (SwitchGoal) $tv))))
      true)
   ())

!(test (collapse (query 0 kb (: $prf (SwitchGoal) $tv))) ())

!(test (collapse (query 4 kb (: $prf (SwitchGoal) $tv)))
   ((: (rule-proof ruleStable baseFact) (SwitchGoal) (STV 1.0 0.63))))

!(test (collapse (query 7 kb (: $prf (SwitchGoal) $tv)))
   ((: (rule-proof ruleStable baseFact) (SwitchGoal) (STV 1.0 0.63))))

!(test (collapse (query 100 kb (: $prf (SwitchGoal) $tv)))
   ((: (rule-proof ruleStable baseFact) (SwitchGoal) (STV 1.0 0.63))))
